### ISSUE TITLE
Using telegram on windows causes swiftgram to frequently receive blank messages.

### ISSUE THREAD

**Issue by moyuwuhen601** [Swiftgram/Telegram-iOS#35]
swiftgram version: 10.14.1
Device: iPhone12
ios version:16.5.1

I logged into my account on swiftgram using the original telegram client on my windows computer, and then my swiftgram frequently pushed blank messages (as shown below). When I clicked on this message, swiftgram would open but there would be no new messages. information. Moreover, this blank push seems to be sent at random times. As long as I open the telegram window on my computer, it may be pushed, but after I minimize telegram, blank push will no longer be sent.
![photo_2024-07-06_17-28-22](https://github.com/Swiftgram/Telegram-iOS/assets/62698541/4c5f4ef0-3a12-4b3e-88fe-9cbbd424a754)

**Comment by moyuwuhen601** [comment]
I would like to add that I have always used telegram on my mobile phone and this problem has never occurred.

**Comment by Kylmakalle** [comment]
https://t.me/swiftgramchat/22

**Comment by Kylmakalle** [comment]
Best what you can do is to Restart your device or update iOS
