### ISSUE TITLE
Sometimes," You have a new message" notification appears

### ISSUE THREAD

**Issue by distrair** [Swiftgram/Telegram-iOS#39]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Describe the issue that you are experiencing
Sometimes, "You have a new message" appears (probably a notification from channel)
### Expected Behavior
Tell us what should happen
Normal notification appears with text and image
### Actual Behavior
Tell us what happens instead
"You have a new message"
### Steps to Reproduce
1. Have notifications enabled for channels
2. Wait until it happens

### Screenshots and Videos 
Remove, if not applicable
![image](https://github.com/user-attachments/assets/aabfa568-7468-497e-92bf-afe1701c998a)
### Environment
**Device:** `iPhone 12 Pro Max`

**iOS version**: `18 Beta 3`

**App version:** `10.14.1 (121)`

**Comment by Kylmakalle** [comment]
https://t.me/swiftgramchat/22
