### ISSUE TITLE
video message only contains a recording from the rear camera

### ISSUE THREAD

**Issue by sazsu** [Swiftgram/Telegram-iOS#42]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
If rear camera is set as the default for video messages and "switch cameras" button is pressed immediately after pressing the "record video message" button, the video message will only contain recording from the rear camera.

### Expected Behavior
Video message should contain recording from the front camera.

### Actual Behavior
Video message only contains recording from the rear camera.

### Steps to Reproduce
1. Set rear camera as default for video messages.
2. Press "record video message" button.
3. Press "switch cameras button" button.
4. Record the video message.

### Environment
**Device:** `iPhone 13 mini`

**iOS version**: `16.1.2`

**App version:** `10.14.1`

**Comment by Kylmakalle** [comment]
> "switch cameras" button is pressed immediately after pressing the "record video message" button

Just don’t do that

**Comment by Kylmakalle** [comment]
Jokes aside, current implementation of "Use rear camera" for Round Videos is the most stable and fastest I've ever got and not sure how more optimized it can be. It's likely your device can't keep up with quickly switching the camera (can't reproduce on a better device with latest public iOS). What may be interesting is an option to quckly change the video message camera direction, but it's rather a feature request that is not tracked here.
