### ISSUE TITLE
Deep Links for telegram to be opened in Swiftgram

### ISSUE THREAD

**Issue by Landxhent** [Swiftgram/Telegram-iOS#60]
Title. For example, to join a chat with a link, you still need an original telegram app. That's why it is needed to keep both apps installed. It's it possible to open telegram links within swiftgram by default?

**Comment by Kylmakalle** [comment]
iOS does not allow users to select which app will be used to open certain type of links.
Use shortcut https://openin.swiftgram.app

https://t.me/swiftgramchat/30485
