### ISSUE TITLE
Revert 11.5.2

### ISSUE THREAD

**Issue by jonttm** [Swiftgram/Telegram-iOS#75]
https://github.com/TelegramMessenger/Telegram-iOS/issues/1649

https://bugs.telegram.org/c/46625

https://reddit.com/r/Telegram/comments/1hhxcb2

**Comment by fcore117** [comment]
I have started to suggest Swiftgram to others too thanks to options to destroy Stories and other tricks to make it more lightweight/slim/compact and clean pure "industrial like" chat experience. My humble suggestion is next time to delay updates little bit to catch official client catastrophic bugs like this. Thanks.

**Comment by jonttm** [comment]
Fixed in 11.5.3

**Comment by fcore117** [comment]
....waiting for arrival into store, thanks.

**Comment by Kylmakalle** [comment]
@fcore117 I've made a longer explanation here https://t.me/iDubTGInsiders/11746
