### ISSUE TITLE
Not buildable on new version of XCode (requires 16.0 instead of 16.2)

### ISSUE THREAD

**Issue by cryptexctl** [Swiftgram/Telegram-iOS#77]
When trying to generate a project on a newer version of XCode, an error is returned 

`Required Xcode version is 16.0, but 16.2 is reported by 'xcode-select -p'`

Are there any local options to fix this problem for me personally? I have no way to roll back to a previous version of XCode normally.

`My host:`

```
OS: macOS 15.2 24C101 arm64 
Host: Mac15,12 
Kernel: Darwin 24.2.0 
CPU: Apple M3 
GPU: Apple M3 
Memory: 16GB 
```

**Comment by cryptexctl** [comment]
Fixed it by adding --overrideXcodeVersion to the command

**Comment by Kylmakalle** [comment]
You can install any Xcode version separately
